blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/harry18456/updownserver/blob/master/README.md
    about: Please report security vulnerabilities privately or via email if possible.
